[package]
name = "openssl-errors"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"

openssl-sys = { version = "0.9.42", path = "../openssl-sys" }

[dev-dependencies]
openssl = { version = "0.10.19", path = "../openssl" }
